// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2xM4crToGxQXBFdCGky5tYxrw8LnBaE',
    appId: '1:354521542765:web:507f7b3d6e922261ad4f64',
    messagingSenderId: '354521542765',
    projectId: 'cmovies-70f5d',
    authDomain: 'cmovies-70f5d.firebaseapp.com',
    storageBucket: 'cmovies-70f5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTQhkmM9c-BJ06X4ghEV2ZRsWLLO9pp4M',
    appId: '1:354521542765:android:070a48277b240979ad4f64',
    messagingSenderId: '354521542765',
    projectId: 'cmovies-70f5d',
    storageBucket: 'cmovies-70f5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsqJEAHYOXjhOIpBDL9EmOg6lD9AkYg1o',
    appId: '1:354521542765:ios:a4f41349ece19ee8ad4f64',
    messagingSenderId: '354521542765',
    projectId: 'cmovies-70f5d',
    storageBucket: 'cmovies-70f5d.appspot.com',
    iosBundleId: 'com.example.cmovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsqJEAHYOXjhOIpBDL9EmOg6lD9AkYg1o',
    appId: '1:354521542765:ios:a4f41349ece19ee8ad4f64',
    messagingSenderId: '354521542765',
    projectId: 'cmovies-70f5d',
    storageBucket: 'cmovies-70f5d.appspot.com',
    iosBundleId: 'com.example.cmovies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB2xM4crToGxQXBFdCGky5tYxrw8LnBaE',
    appId: '1:354521542765:web:5e3f4a5e44707844ad4f64',
    messagingSenderId: '354521542765',
    projectId: 'cmovies-70f5d',
    authDomain: 'cmovies-70f5d.firebaseapp.com',
    storageBucket: 'cmovies-70f5d.appspot.com',
  );

}